version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - git clone https://github.com/gcabreranl/sam-test.git
      - cd sam-test
      - sam deploy -t template1.yaml --no-confirm-changeset --s3-bucket sam-testing-deploy