version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - sam deploy -t template1.yaml --no-confirm-changeset --s3-bucket sam-testing-deploy --parameter-overrides ApiId=mjubyj8ifk