version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samtest"
S3Bucket = "sam-testing-deploy"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
s3_prefix = "samtest"
