AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  lambda1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: app3/
      MemorySize: 128
      Events:
        samTest:
          Type: Api
          Properties:
            Path: /test/{proxy+}
            Method: ANY
  lambda2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: app2/
      MemorySize: 128
      Events:
        samTest:
          Type: Api
          Properties:
            Path: /test2/{proxy+}
            Method: ANY
  lambda3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: app/
      MemorySize: 128
      Events:
        samTest:
          Type: Api
          Properties:
            Path: /test3/{proxy+}
            Method: ANY